### ISSUE TITLE
RethinkDB part is missing

### ISSUE THREAD

**Issue by Bojhan** [thejsj/sharejs-rethinkdb-example#2]
It seems that running this requires certain RethinkDB database modelling. However I dont see that in this example?

```
Stream : write ->  {"a":"init","protocol":0,"id":"303139510dbf76d5002a4d0dbaecdc68"}
Unhandled rejection RqlRuntimeError: Table `sharejs.documents_ops` does not exist in:
r.table("documents_ops").changes()
^^^^^^^^^^^^^^^^^^^^^^^^          
    at RqlRuntimeError.RqlServerError (/Applications/MAMP/htdocs/RGT-base/node_modules/rethinkdb/errors.js:39:13)
    at new RqlRuntimeError (/Applications/MAMP/htdocs/RGT-base/node_modules/rethinkdb/errors.js:51:50)
    at mkErr (/Applications/MAMP/htdocs/RGT-base/node_modules/rethinkdb/util.js:173:10)
    at TcpConnection.Connection._processResponse (/Applications/MAMP/htdocs/RGT-base/node_modules/rethinkdb/net.js:138:16)
    at TcpConnection.Connection._data (/Applications/MAMP/htdocs/RGT-base/node_modules/rethinkdb/net.js:104:12)
    at Socket.<anonymous> (/Applications/MAMP/htdocs/RGT-base/node_modules/rethinkdb/net.js:494:32)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21)
Client : message ->  { a: 'bs',
  s: { documents: { sharejs_example: null, helloworld: null } } }
Unhandled rejection ReqlRuntimeError: Cannot perform read: Primary replica for shard ["", +inf) not available (server f8225666-71cf-4f72-92a2-1a7288e7000b is not ready) in:
r.table("documents_ops").orderBy({
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    index: "v"
    ^^^^^^^^^^
}).filter({
^^^^^^^^^^^
    name: "helloworld"
    ^^^^^^^^^^^^^^^^^^
}).filter(function(var_2) {
^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return var_2("v").ge(0)
    ^^^^^^^^^^^^^^^^^^^^^^^
})
^^

    at Connection._processResponse (/Applications/MAMP/htdocs/RGT-base/node_modules/livedb-rethinkdb/node_modules/rethinkdbdash/lib/connection.js:184:35)
    at Socket.<anonymous> (/Applications/MAMP/htdocs/RGT-base/node_modules/livedb-rethinkdb/node_modules/rethinkdbdash/lib/connection.js:117:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21)
```

**Comment by Bojhan** [comment]
Ahh resolved it, this is just on initial load.
